// ⚠️ GENERATED by 'npm run db:types' (supabase gen types). DO NOT EDIT.
// App-facing convenience aliases live in types/db.ts — import from '@/types/db'.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      page_translations: {
        Row: {
          content: Json | null
          description: string | null
          engine: string | null
          locale: string
          page_id: string
          source_hash: string
          status: Database["public"]["Enums"]["translation_status"]
          title: string | null
          translated_at: string
        }
        Insert: {
          content?: Json | null
          description?: string | null
          engine?: string | null
          locale: string
          page_id: string
          source_hash: string
          status?: Database["public"]["Enums"]["translation_status"]
          title?: string | null
          translated_at?: string
        }
        Update: {
          content?: Json | null
          description?: string | null
          engine?: string | null
          locale?: string
          page_id?: string
          source_hash?: string
          status?: Database["public"]["Enums"]["translation_status"]
          title?: string | null
          translated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "page_translations_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      page_versions: {
        Row: {
          change_summary: string | null
          content: Json | null
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          is_published: boolean
          page_id: string
          project_id: string
          published_at: string | null
          restored_from_version_id: string | null
          title: string
          version_number: number
        }
        Insert: {
          change_summary?: string | null
          content?: Json | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_published?: boolean
          page_id: string
          project_id: string
          published_at?: string | null
          restored_from_version_id?: string | null
          title: string
          version_number: number
        }
        Update: {
          change_summary?: string | null
          content?: Json | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_published?: boolean
          page_id?: string
          project_id?: string
          published_at?: string | null
          restored_from_version_id?: string | null
          title?: string
          version_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "page_versions_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "page_versions_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "page_versions_restored_from_version_id_fkey"
            columns: ["restored_from_version_id"]
            isOneToOne: false
            referencedRelation: "page_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      pages: {
        Row: {
          content: Json | null
          cover_image_url: string | null
          cover_style: Database["public"]["Enums"]["cover_style"] | null
          created_at: string
          created_by: string | null
          description: string | null
          draft_content: Json | null
          draft_description: string | null
          draft_title: string | null
          draft_updated_at: string | null
          hidden: boolean
          icon: string | null
          id: string
          kind: Database["public"]["Enums"]["page_kind"]
          layout: Json
          link_href: string | null
          link_title: string | null
          no_index: boolean
          order_index: number
          parent_id: string | null
          path: string
          primary_tag: string | null
          project_id: string
          search_vector: unknown
          slug: string
          status: Database["public"]["Enums"]["page_status"]
          tags: string[]
          title: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          content?: Json | null
          cover_image_url?: string | null
          cover_style?: Database["public"]["Enums"]["cover_style"] | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          draft_content?: Json | null
          draft_description?: string | null
          draft_title?: string | null
          draft_updated_at?: string | null
          hidden?: boolean
          icon?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["page_kind"]
          layout?: Json
          link_href?: string | null
          link_title?: string | null
          no_index?: boolean
          order_index?: number
          parent_id?: string | null
          path: string
          primary_tag?: string | null
          project_id: string
          search_vector?: unknown
          slug: string
          status?: Database["public"]["Enums"]["page_status"]
          tags?: string[]
          title: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          content?: Json | null
          cover_image_url?: string | null
          cover_style?: Database["public"]["Enums"]["cover_style"] | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          draft_content?: Json | null
          draft_description?: string | null
          draft_title?: string | null
          draft_updated_at?: string | null
          hidden?: boolean
          icon?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["page_kind"]
          layout?: Json
          link_href?: string | null
          link_title?: string | null
          no_index?: boolean
          order_index?: number
          parent_id?: string | null
          path?: string
          primary_tag?: string | null
          project_id?: string
          search_vector?: unknown
          slug?: string
          status?: Database["public"]["Enums"]["page_status"]
          tags?: string[]
          title?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pages_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pages_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          cover_image_url: string | null
          created_at: string
          custom_domain: string | null
          description: string | null
          enabled_locales: string[]
          icon: string | null
          id: string
          name: string
          slug: string
          theme: Json
          updated_at: string
          user_id: string
          visibility: string
        }
        Insert: {
          cover_image_url?: string | null
          created_at?: string
          custom_domain?: string | null
          description?: string | null
          enabled_locales?: string[]
          icon?: string | null
          id?: string
          name: string
          slug: string
          theme?: Json
          updated_at?: string
          user_id: string
          visibility?: string
        }
        Update: {
          cover_image_url?: string | null
          created_at?: string
          custom_domain?: string | null
          description?: string | null
          enabled_locales?: string[]
          icon?: string | null
          id?: string
          name?: string
          slug?: string
          theme?: Json
          updated_at?: string
          user_id?: string
          visibility?: string
        }
        Relationships: []
      }
      translation_jobs: {
        Row: {
          attempts: number
          created_at: string
          error: string | null
          id: string
          locale: string
          page_id: string
          status: Database["public"]["Enums"]["translation_job_status"]
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          error?: string | null
          id?: string
          locale: string
          page_id: string
          status?: Database["public"]["Enums"]["translation_job_status"]
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          error?: string | null
          id?: string
          locale?: string
          page_id?: string
          status?: Database["public"]["Enums"]["translation_job_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "translation_jobs_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      translation_memory: {
        Row: {
          engine: string | null
          locale: string
          source_hash: string
          source_text: string
          target_text: string
          updated_at: string
        }
        Insert: {
          engine?: string | null
          locale: string
          source_hash: string
          source_text: string
          target_text: string
          updated_at?: string
        }
        Update: {
          engine?: string | null
          locale?: string
          source_hash?: string
          source_text?: string
          target_text?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      blocknote_text: { Args: { content: Json }; Returns: string }
      create_page_version: {
        Args: {
          p_change_summary?: string
          p_is_published?: boolean
          p_page_id: string
        }
        Returns: string
      }
      enqueue_page_translations: {
        Args: { p_page_id: string }
        Returns: undefined
      }
      publish_page: { Args: { p_page_id: string }; Returns: undefined }
      rename_page: {
        Args: { p_page_id: string; p_title: string }
        Returns: string
      }
      request_page_translations: {
        Args: { p_locales: string[]; p_page_id: string }
        Returns: number
      }
      request_translations: {
        Args: {
          p_locales: string[]
          p_only_stale?: boolean
          p_project_id: string
        }
        Returns: number
      }
      restore_page_version: { Args: { p_version_id: string }; Returns: string }
      search_pages: {
        Args: { p_limit?: number; p_project_slug: string; p_query: string }
        Returns: {
          content: Json
          description: string
          path: string
          title: string
        }[]
      }
      set_translation_reviewed: {
        Args: { p_locale: string; p_page_id: string; p_reviewed: boolean }
        Returns: undefined
      }
    }
    Enums: {
      cover_style: "full" | "content"
      page_kind: "document" | "group" | "link"
      page_status: "draft" | "published"
      translation_job_status: "pending" | "running" | "done" | "failed"
      translation_status: "machine" | "reviewed" | "outdated"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      cover_style: ["full", "content"],
      page_kind: ["document", "group", "link"],
      page_status: ["draft", "published"],
      translation_job_status: ["pending", "running", "done", "failed"],
      translation_status: ["machine", "reviewed", "outdated"],
    },
  },
} as const
