// ⚠️ GENERATED by 'npm run db:types' (supabase gen types). DO NOT EDIT.
// App-facing convenience aliases live in types/db.ts — import from '@/types/db'.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      analytics_insights: {
        Row: {
          created_at: string
          id: string
          period_end: string
          period_start: string
          project_id: string
          summary: Json
        }
        Insert: {
          created_at?: string
          id?: string
          period_end: string
          period_start: string
          project_id: string
          summary: Json
        }
        Update: {
          created_at?: string
          id?: string
          period_end?: string
          period_start?: string
          project_id?: string
          summary?: Json
        }
        Relationships: [
          {
            foreignKeyName: "analytics_insights_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      content_entities: {
        Row: {
          change_note: string | null
          changed_at: string | null
          created_at: string
          description: string | null
          id: string
          name: string
          project_id: string
          reference_image_url: string | null
          updated_at: string
          version_tag: string | null
        }
        Insert: {
          change_note?: string | null
          changed_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name: string
          project_id: string
          reference_image_url?: string | null
          updated_at?: string
          version_tag?: string | null
        }
        Update: {
          change_note?: string | null
          changed_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          project_id?: string
          reference_image_url?: string | null
          updated_at?: string
          version_tag?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "content_entities_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      entity_audit_jobs: {
        Row: {
          attempts: number
          created_at: string
          entity_id: string
          error: string | null
          id: string
          page_id: string
          status: Database["public"]["Enums"]["entity_audit_job_status"]
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          entity_id: string
          error?: string | null
          id?: string
          page_id: string
          status?: Database["public"]["Enums"]["entity_audit_job_status"]
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          entity_id?: string
          error?: string | null
          id?: string
          page_id?: string
          status?: Database["public"]["Enums"]["entity_audit_job_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "entity_audit_jobs_entity_id_fkey"
            columns: ["entity_id"]
            isOneToOne: false
            referencedRelation: "content_entities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entity_audit_jobs_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      github_sync_events: {
        Row: {
          commit_sha: string
          detected_at: string
          id: string
          project_id: string
          status: Database["public"]["Enums"]["github_sync_event_status"]
          summary: string | null
          synced_at: string | null
          synced_by: string | null
        }
        Insert: {
          commit_sha: string
          detected_at?: string
          id?: string
          project_id: string
          status?: Database["public"]["Enums"]["github_sync_event_status"]
          summary?: string | null
          synced_at?: string | null
          synced_by?: string | null
        }
        Update: {
          commit_sha?: string
          detected_at?: string
          id?: string
          project_id?: string
          status?: Database["public"]["Enums"]["github_sync_event_status"]
          summary?: string | null
          synced_at?: string | null
          synced_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "github_sync_events_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      graph_extract_jobs: {
        Row: {
          attempts: number
          created_at: string
          error: string | null
          id: string
          page_id: string
          status: Database["public"]["Enums"]["graph_extract_job_status"]
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          error?: string | null
          id?: string
          page_id: string
          status?: Database["public"]["Enums"]["graph_extract_job_status"]
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          error?: string | null
          id?: string
          page_id?: string
          status?: Database["public"]["Enums"]["graph_extract_job_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "graph_extract_jobs_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      mcp_api_keys: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          key_hash: string
          key_prefix: string | null
          label: string | null
          last_used_at: string | null
          revoked_at: string | null
          scopes: string[]
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          key_hash: string
          key_prefix?: string | null
          label?: string | null
          last_used_at?: string | null
          revoked_at?: string | null
          scopes?: string[]
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          key_hash?: string
          key_prefix?: string | null
          label?: string | null
          last_used_at?: string | null
          revoked_at?: string | null
          scopes?: string[]
        }
        Relationships: []
      }
      mcp_audit_log: {
        Row: {
          args: Json | null
          created_at: string
          error: string | null
          id: string
          key_id: string | null
          page_path: string | null
          project_slug: string | null
          status: string
          tool: string
        }
        Insert: {
          args?: Json | null
          created_at?: string
          error?: string | null
          id?: string
          key_id?: string | null
          page_path?: string | null
          project_slug?: string | null
          status?: string
          tool: string
        }
        Update: {
          args?: Json | null
          created_at?: string
          error?: string | null
          id?: string
          key_id?: string | null
          page_path?: string | null
          project_slug?: string | null
          status?: string
          tool?: string
        }
        Relationships: [
          {
            foreignKeyName: "mcp_audit_log_key_id_fkey"
            columns: ["key_id"]
            isOneToOne: false
            referencedRelation: "mcp_api_keys"
            referencedColumns: ["id"]
          },
        ]
      }
      page_entity_links: {
        Row: {
          block_path: string | null
          created_at: string
          entity_id: string
          excerpt: string | null
          id: string
          kind: Database["public"]["Enums"]["entity_link_kind"]
          note: string | null
          page_id: string
          reviewed_at: string
          source: string
          status: Database["public"]["Enums"]["entity_link_status"]
          updated_at: string
        }
        Insert: {
          block_path?: string | null
          created_at?: string
          entity_id: string
          excerpt?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["entity_link_kind"]
          note?: string | null
          page_id: string
          reviewed_at?: string
          source?: string
          status?: Database["public"]["Enums"]["entity_link_status"]
          updated_at?: string
        }
        Update: {
          block_path?: string | null
          created_at?: string
          entity_id?: string
          excerpt?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["entity_link_kind"]
          note?: string | null
          page_id?: string
          reviewed_at?: string
          source?: string
          status?: Database["public"]["Enums"]["entity_link_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "page_entity_links_entity_id_fkey"
            columns: ["entity_id"]
            isOneToOne: false
            referencedRelation: "content_entities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "page_entity_links_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      page_events: {
        Row: {
          comment: string | null
          created_at: string
          event_type: Database["public"]["Enums"]["page_event_type"]
          helpful: boolean | null
          id: string
          locale: string | null
          page_id: string | null
          project_id: string
          query_text: string | null
        }
        Insert: {
          comment?: string | null
          created_at?: string
          event_type: Database["public"]["Enums"]["page_event_type"]
          helpful?: boolean | null
          id?: string
          locale?: string | null
          page_id?: string | null
          project_id: string
          query_text?: string | null
        }
        Update: {
          comment?: string | null
          created_at?: string
          event_type?: Database["public"]["Enums"]["page_event_type"]
          helpful?: boolean | null
          id?: string
          locale?: string | null
          page_id?: string | null
          project_id?: string
          query_text?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "page_events_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "page_events_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      page_links: {
        Row: {
          created_at: string
          from_page_id: string
          id: string
          link_text: string | null
          to_page_id: string
        }
        Insert: {
          created_at?: string
          from_page_id: string
          id?: string
          link_text?: string | null
          to_page_id: string
        }
        Update: {
          created_at?: string
          from_page_id?: string
          id?: string
          link_text?: string | null
          to_page_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "page_links_from_page_id_fkey"
            columns: ["from_page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "page_links_to_page_id_fkey"
            columns: ["to_page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      page_translations: {
        Row: {
          content: Json | null
          description: string | null
          engine: string | null
          locale: string
          page_id: string
          source_hash: string
          status: Database["public"]["Enums"]["translation_status"]
          title: string | null
          translated_at: string
        }
        Insert: {
          content?: Json | null
          description?: string | null
          engine?: string | null
          locale: string
          page_id: string
          source_hash: string
          status?: Database["public"]["Enums"]["translation_status"]
          title?: string | null
          translated_at?: string
        }
        Update: {
          content?: Json | null
          description?: string | null
          engine?: string | null
          locale?: string
          page_id?: string
          source_hash?: string
          status?: Database["public"]["Enums"]["translation_status"]
          title?: string | null
          translated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "page_translations_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      page_versions: {
        Row: {
          change_summary: string | null
          content: Json | null
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          is_published: boolean
          page_id: string
          project_id: string
          published_at: string | null
          restored_from_version_id: string | null
          title: string
          version_number: number
        }
        Insert: {
          change_summary?: string | null
          content?: Json | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_published?: boolean
          page_id: string
          project_id: string
          published_at?: string | null
          restored_from_version_id?: string | null
          title: string
          version_number: number
        }
        Update: {
          change_summary?: string | null
          content?: Json | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_published?: boolean
          page_id?: string
          project_id?: string
          published_at?: string | null
          restored_from_version_id?: string | null
          title?: string
          version_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "page_versions_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "page_versions_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "page_versions_restored_from_version_id_fkey"
            columns: ["restored_from_version_id"]
            isOneToOne: false
            referencedRelation: "page_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      pages: {
        Row: {
          content: Json | null
          cover_image_url: string | null
          cover_style: Database["public"]["Enums"]["cover_style"] | null
          created_at: string
          created_by: string | null
          description: string | null
          draft_content: Json | null
          draft_description: string | null
          draft_title: string | null
          draft_updated_at: string | null
          github_path: string | null
          hidden: boolean
          icon: string | null
          id: string
          kind: Database["public"]["Enums"]["page_kind"]
          layout: Json
          link_href: string | null
          link_title: string | null
          no_index: boolean
          order_index: number
          parent_id: string | null
          path: string
          primary_tag: string | null
          project_id: string
          search_vector: unknown
          slug: string
          status: Database["public"]["Enums"]["page_status"]
          tags: string[]
          title: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          content?: Json | null
          cover_image_url?: string | null
          cover_style?: Database["public"]["Enums"]["cover_style"] | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          draft_content?: Json | null
          draft_description?: string | null
          draft_title?: string | null
          draft_updated_at?: string | null
          github_path?: string | null
          hidden?: boolean
          icon?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["page_kind"]
          layout?: Json
          link_href?: string | null
          link_title?: string | null
          no_index?: boolean
          order_index?: number
          parent_id?: string | null
          path: string
          primary_tag?: string | null
          project_id: string
          search_vector?: unknown
          slug: string
          status?: Database["public"]["Enums"]["page_status"]
          tags?: string[]
          title: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          content?: Json | null
          cover_image_url?: string | null
          cover_style?: Database["public"]["Enums"]["cover_style"] | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          draft_content?: Json | null
          draft_description?: string | null
          draft_title?: string | null
          draft_updated_at?: string | null
          github_path?: string | null
          hidden?: boolean
          icon?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["page_kind"]
          layout?: Json
          link_href?: string | null
          link_title?: string | null
          no_index?: boolean
          order_index?: number
          parent_id?: string | null
          path?: string
          primary_tag?: string | null
          project_id?: string
          search_vector?: unknown
          slug?: string
          status?: Database["public"]["Enums"]["page_status"]
          tags?: string[]
          title?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pages_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pages_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          cover_image_url: string | null
          created_at: string
          custom_domain: string | null
          description: string | null
          enabled_locales: string[]
          github_branch: string
          github_last_synced_sha: string | null
          github_repo: string | null
          icon: string | null
          id: string
          name: string
          slug: string
          theme: Json
          updated_at: string
          user_id: string
          visibility: string
        }
        Insert: {
          cover_image_url?: string | null
          created_at?: string
          custom_domain?: string | null
          description?: string | null
          enabled_locales?: string[]
          github_branch?: string
          github_last_synced_sha?: string | null
          github_repo?: string | null
          icon?: string | null
          id?: string
          name: string
          slug: string
          theme?: Json
          updated_at?: string
          user_id: string
          visibility?: string
        }
        Update: {
          cover_image_url?: string | null
          created_at?: string
          custom_domain?: string | null
          description?: string | null
          enabled_locales?: string[]
          github_branch?: string
          github_last_synced_sha?: string | null
          github_repo?: string | null
          icon?: string | null
          id?: string
          name?: string
          slug?: string
          theme?: Json
          updated_at?: string
          user_id?: string
          visibility?: string
        }
        Relationships: []
      }
      translation_glossary: {
        Row: {
          created_at: string
          id: string
          notes: string | null
          term: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          notes?: string | null
          term: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          notes?: string | null
          term?: string
          updated_at?: string
        }
        Relationships: []
      }
      translation_jobs: {
        Row: {
          attempts: number
          created_at: string
          error: string | null
          id: string
          locale: string
          page_id: string
          status: Database["public"]["Enums"]["translation_job_status"]
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          error?: string | null
          id?: string
          locale: string
          page_id: string
          status?: Database["public"]["Enums"]["translation_job_status"]
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          error?: string | null
          id?: string
          locale?: string
          page_id?: string
          status?: Database["public"]["Enums"]["translation_job_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "translation_jobs_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      translation_memory: {
        Row: {
          engine: string | null
          locale: string
          source_hash: string
          source_text: string
          target_text: string
          updated_at: string
        }
        Insert: {
          engine?: string | null
          locale: string
          source_hash: string
          source_text: string
          target_text: string
          updated_at?: string
        }
        Update: {
          engine?: string | null
          locale?: string
          source_hash?: string
          source_text?: string
          target_text?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      blocknote_text: { Args: { content: Json }; Returns: string }
      create_page_version: {
        Args: {
          p_change_summary?: string
          p_is_published?: boolean
          p_page_id: string
        }
        Returns: string
      }
      enqueue_page_translations: {
        Args: { p_page_id: string }
        Returns: undefined
      }
      mcp_create_page_version: {
        Args: { p_change_summary?: string; p_page_id: string }
        Returns: string
      }
      mcp_publish_page: { Args: { p_page_id: string }; Returns: undefined }
      mcp_rename_page: {
        Args: { p_page_id: string; p_title: string }
        Returns: string
      }
      mcp_restore_page_version: {
        Args: { p_version_id: string }
        Returns: string
      }
      mcp_search_pages: {
        Args: {
          p_limit?: number
          p_project_slug?: string
          p_query: string
          p_tag?: string
        }
        Returns: {
          description: string
          path: string
          project_slug: string
          rank: number
          snippet: string
          title: string
        }[]
      }
      publish_page: { Args: { p_page_id: string }; Returns: undefined }
      rename_page: {
        Args: { p_page_id: string; p_title: string }
        Returns: string
      }
      request_page_translations: {
        Args: { p_locales: string[]; p_page_id: string }
        Returns: number
      }
      request_translations: {
        Args: {
          p_locales: string[]
          p_only_stale?: boolean
          p_project_id: string
        }
        Returns: number
      }
      restore_page_version: { Args: { p_version_id: string }; Returns: string }
      search_pages: {
        Args: { p_limit?: number; p_project_slug: string; p_query: string }
        Returns: {
          content: Json
          description: string
          path: string
          title: string
        }[]
      }
      set_translation_reviewed: {
        Args: { p_locale: string; p_page_id: string; p_reviewed: boolean }
        Returns: undefined
      }
    }
    Enums: {
      cover_style: "full" | "content"
      entity_audit_job_status: "pending" | "running" | "done" | "failed"
      entity_link_kind: "text" | "media" | "both"
      entity_link_status: "ok" | "stale" | "gap"
      github_sync_event_status: "pending" | "synced" | "dismissed"
      graph_extract_job_status: "pending" | "running" | "done" | "failed"
      page_event_type:
        | "search_query"
        | "search_zero_result"
        | "pdf_download"
        | "copy_page"
        | "view_markdown"
        | "open_chatgpt"
        | "open_claude"
        | "mcp_connect_click"
        | "feedback"
      page_kind: "document" | "group" | "link"
      page_status: "draft" | "published"
      translation_job_status: "pending" | "running" | "done" | "failed"
      translation_status: "machine" | "reviewed" | "outdated"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      cover_style: ["full", "content"],
      entity_audit_job_status: ["pending", "running", "done", "failed"],
      entity_link_kind: ["text", "media", "both"],
      entity_link_status: ["ok", "stale", "gap"],
      github_sync_event_status: ["pending", "synced", "dismissed"],
      graph_extract_job_status: ["pending", "running", "done", "failed"],
      page_event_type: [
        "search_query",
        "search_zero_result",
        "pdf_download",
        "copy_page",
        "view_markdown",
        "open_chatgpt",
        "open_claude",
        "mcp_connect_click",
        "feedback",
      ],
      page_kind: ["document", "group", "link"],
      page_status: ["draft", "published"],
      translation_job_status: ["pending", "running", "done", "failed"],
      translation_status: ["machine", "reviewed", "outdated"],
    },
  },
} as const
