// Hand-maintained convenience layer over the generated Supabase types.
//
// `types/database.ts` is 100% generated by `supabase gen types` and must NOT be
// edited — regenerate it freely. These ergonomic aliases live here instead, so
// regenerating the schema types never loses them. Import app-facing types from
// `@/types/db` (which also re-exports everything from the generated file).

import type { Database } from './database'

export * from './database'

export type Project = Database['public']['Tables']['projects']['Row']
export type ProjectInsert = Database['public']['Tables']['projects']['Insert']
export type ProjectUpdate = Database['public']['Tables']['projects']['Update']

export type Page = Database['public']['Tables']['pages']['Row']
export type PageInsert = Database['public']['Tables']['pages']['Insert']
export type PageUpdate = Database['public']['Tables']['pages']['Update']

export type PageKind = Database['public']['Enums']['page_kind']
export type PageStatus = Database['public']['Enums']['page_status']

export type PageWithChildren = Page & { children: PageWithChildren[] }

export type PageVersion = Database['public']['Tables']['page_versions']['Row']

export type PageTranslation = Database['public']['Tables']['page_translations']['Row']
export type TranslationJob = Database['public']['Tables']['translation_jobs']['Row']
export type TranslationStatus = Database['public']['Enums']['translation_status']
export type TranslationJobStatus = Database['public']['Enums']['translation_job_status']

export type GithubSyncEvent = Database['public']['Tables']['github_sync_events']['Row']
export type GithubSyncEventStatus = Database['public']['Enums']['github_sync_event_status']

export type TranslationGlossaryTerm = Database['public']['Tables']['translation_glossary']['Row']

export type PageEvent = Database['public']['Tables']['page_events']['Row']
export type PageEventInsert = Database['public']['Tables']['page_events']['Insert']
export type PageEventType = Database['public']['Enums']['page_event_type']
export type AnalyticsInsight = Database['public']['Tables']['analytics_insights']['Row']

export type ContentEntity = Database['public']['Tables']['content_entities']['Row']
export type PageEntityLink = Database['public']['Tables']['page_entity_links']['Row']
export type EntityLinkKind = Database['public']['Enums']['entity_link_kind']
export type EntityLinkStatus = Database['public']['Enums']['entity_link_status']
export type PageLink = Database['public']['Tables']['page_links']['Row']
export type GraphExtractJob = Database['public']['Tables']['graph_extract_jobs']['Row']
export type EntityAuditJob = Database['public']['Tables']['entity_audit_jobs']['Row']
export type EntitySuggestJob = Database['public']['Tables']['entity_suggest_jobs']['Row']
