// Hand-maintained convenience layer over the generated Supabase types.
//
// `types/database.ts` is 100% generated by `supabase gen types` and must NOT be
// edited — regenerate it freely. These ergonomic aliases live here instead, so
// regenerating the schema types never loses them. Import app-facing types from
// `@/types/db` (which also re-exports everything from the generated file).

import type { Database } from './database'

export * from './database'

export type Project = Database['public']['Tables']['projects']['Row']
export type ProjectInsert = Database['public']['Tables']['projects']['Insert']
export type ProjectUpdate = Database['public']['Tables']['projects']['Update']

export type Page = Database['public']['Tables']['pages']['Row']
export type PageInsert = Database['public']['Tables']['pages']['Insert']
export type PageUpdate = Database['public']['Tables']['pages']['Update']

export type PageKind = Database['public']['Enums']['page_kind']
export type PageStatus = Database['public']['Enums']['page_status']

export type PageWithChildren = Page & { children: PageWithChildren[] }

export type PageVersion = Database['public']['Tables']['page_versions']['Row']

export type PageTranslation = Database['public']['Tables']['page_translations']['Row']
export type TranslationJob = Database['public']['Tables']['translation_jobs']['Row']
export type TranslationStatus = Database['public']['Enums']['translation_status']
export type TranslationJobStatus = Database['public']['Enums']['translation_job_status']
