#!/usr/bin/env bash
# Regenerate the Supabase types. Run after any schema migration:
#   npm run db:types
#
# Writes types/database.ts (100% generated). The convenience aliases used across
# the app live in types/db.ts and are NEVER touched by this — so regenerating is
# always safe and you never lose them.
set -euo pipefail

OUT="types/database.ts"
{
  echo "// ⚠️ GENERATED by 'npm run db:types' (supabase gen types). DO NOT EDIT."
  echo "// App-facing convenience aliases live in types/db.ts — import from '@/types/db'."
  echo ""
  supabase gen types typescript --linked
} > "$OUT"

echo "Wrote $OUT"
